# Generated by Django 3.1 on 2021-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('capital', models.IntegerField()),
                ('industry', models.CharField(max_length=150)),
                ('listed_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StockChips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.IntegerField()),
                ('margin_purchase', models.IntegerField()),
                ('short_sale', models.IntegerField()),
                ('foreign', models.IntegerField()),
                ('trust', models.IntegerField()),
                ('dealer', models.IntegerField()),
                ('ftd_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.IntegerField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('shares', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('pe', models.FloatField()),
                ('pb', models.FloatField()),
                ('yield_rate', models.FloatField()),
            ],
        ),
    ]
